# Aula 15 - Algoritmos e Estrutura de Dados 
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np
print(np.__version__)

1.26.4


⚫2- Crie uma matriz 1D com números de 0 a 9

In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [6]:
print(np.full((3, 3), True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de ‘arr’

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

⚫5- Substitua todos os números ímpares arr por -1

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print (arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [15]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [20]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

⚫3 - Empilhe- Empilhe matrizes verticalmente:

In [22]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])
resultado = np.vstack((a, b))

print(resultado)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


⚫4- Empilhe as matrizes horizontalmente:

In [23]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

resultado = np.hstack((a, b))

print(resultado)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [24]:
a = np.array([1,2,3])

In [25]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Difícil 

⚫1- Calcule as contagens de valores únicos na linha.

In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

In [ ]:
def counts_of_all_values_rowwise(arr2d):
    # Valores exclusivos e suas contagens de linha inteligente
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    # Contagens de todos os valores linha inteligente
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(np.arange(1,11))
counts_of_all_values_rowwise(arr)